### ISSUE TITLE
RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.

### ISSUE THREAD

**Issue by lorddaedra** [omab/python-social-auth#755]
Please, check your social.apps.django_app.default.fields.JSONField and refactor code, need to remove usage of SubfieldBase...
https://docs.djangoproject.com/en/1.8/releases/1.8/#subfieldbase 

Tested on Django1.9a1, Python 3.5

**Comment by lorddaedra** [comment]
Also I suggest to use https://docs.djangoproject.com/en/1.9/ref/contrib/postgres/fields/#django.contrib.postgres.fields.JSONField

if Django >= 1.9 and django.contrib.postgres in installed apps...

**Comment by neographikal** [comment]
With the Django 1.10 dev this gives a error indeed, when you try to create the migrations.

**Comment by AndreasBackx** [comment]
I'm getting the same error twice when starting the development server. I'm using python-social-auth (0.2.14) and Django (1.9.1).

**Comment by webjunkie** [comment]
Also fixed by #813

**Comment by genxstylez** [comment]
when is this releasing?

**Comment by matheusjardimb** [comment]
News on this topic?

**Comment by rokcarl** [comment]
I get this warning on latest 0.2.21 version, so not yet fixed.

**Comment by rudyryk** [comment]
I can see warnings with the Django 1.9.11

**Comment by omab** [comment]
This got fixed.
